use argparse
cyrusbehr/YOLOv8-TensorRT-CPP pull request #44
Opened 2024-02-20 19:24 UTC by IamShubhamGupto

- use `argparse` to simplify onnx export

2024-02-20 21:39 UTC, cyrusbehr requested changes
Please also change the readme file to reflect the change. In the readme, I demonstrate how to use the script, so you need to update that line of code.

2024-02-21 03:41 UTC, IamShubhamGupto commented
@cyrusbehr please review them now

2024-02-21 14:23 UTC, cyrusbehr approved these changes

2024-02-21 14:23 UTC, merged

2024-02-21 14:26 UTC, cyrusbehr commented
@all-contributors please add @IamShubhamGupto for code